services:
  db:
    image: postgres:17.4-alpine3.21
    container_name: test_db
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=p8sSW0rd
      - POSTGRES_DB=betternewsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - betternews-network

networks:
  betternews-network:
    driver: bridge

volumes:
  postgres-data:
